apiVersion: networking.serving.volcano.sh/v1alpha1
kind: ModelRoute
metadata:
  name: deep-seek-r1
  namespace: vllm-project
spec:
  modelName: "ds_r1"
  rules:
  - name: "default"
    targetModels:
    - modelServerName: "deepseek-pd"
---
apiVersion: networking.serving.volcano.sh/v1alpha1
kind: ModelServer
metadata:
  name: deepseek-pd
  namespace: vllm-project
spec:
  inferenceEngine: vLLM
  model: "ds_r1"
  workloadPort:
    port: 7100
    protocol: http
  workloadSelector:
    matchLabels:
      modelserving.volcano.sh/name: deepseek-pd
    pdGroup:
      groupKey: "modelserving.volcano.sh/group-name"
      prefillLabels:
        modelserving.volcano.sh/role: prefill
        modelserving.volcano.sh/entry: "true"
      decodeLabels:
        modelserving.volcano.sh/role: decode
        modelserving.volcano.sh/entry: "true"
  trafficPolicy:
    timeout: "300s"
    retry:
      attempts: 3
      retryInterval: "150ms"
  kvConnector:
    type: mooncake